<?php

namespace App\Services;

use FPDF;

class ProjectReportPdf extends FPDF
{
    private $reportTitle = 'PEO Project Monitoring Report';
    private $generatedAt = '';
    private $filterLabel = 'All Projects';
    private $generatedBy = '';

    private const PDF_REMARKS_MAX_LENGTH = 8000;
    private const ROW_MIN_HEIGHT_MM = 9.0;
    private const ROW_LINE_HEIGHT_MM = 4.2;
    private const ROW_VERTICAL_PADDING_MM = 1.4;

    public function sanitizeForPdf(string $s, int $maxLength = 0): string
    {
        // Step 1 — Encoding conversion (matches original controller logic)
        if (extension_loaded('iconv')) {
            $converted = iconv('UTF-8', 'windows-1252//TRANSLIT//IGNORE', $s);
            $s = ($converted !== false && $converted !== '') ? $converted : preg_replace('/[^\x20-\x7E]/', '?', $s);
        } else {
            $s = preg_replace('/[^\x20-\x7E]/', '?', $s);
        }

        // Step 2 — Strip dangerous control characters that can corrupt PDF streams.
        // Keep \t (0x09), \n (0x0A), \r (0x0D) — FPDF uses these for layout.
        // Remove: null byte, 0x01-0x08, 0x0B (VT), 0x0C (FF), 0x0E-0x1F.
        $s = preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F]/', '', $s);

        // Step 3 — Normalise line endings to \n
        $s = str_replace(["\r\n", "\r"], "\n", $s);

        // Step 4 — Enforce length cap for PDF rendering only
        if ($maxLength > 0 && mb_strlen($s) > $maxLength) {
            $s = mb_substr($s, 0, $maxLength) . "\n\n[... truncated for PDF. Full text available in the system ...]";
        }

        return $s;
    }

    // ── Kept for backward-compatibility with controllers that still use
    //    the inline clean() closure. New code should use sanitizeForPdf(). ──

    public function setGeneratedAt(string $date): void
    {
        $this->generatedAt = $date;
    }

    public function setFilterLabel(string $label): void
    {
        $this->filterLabel = $label;
    }

    public function setGeneratedBy(string $name): void
    {
        $this->generatedBy = trim($name) !== '' ? trim($name) : 'System';
    }

    private bool $suppressHeader = false;

    public function suppressAutoHeader(bool $val = true): void
    {
        $this->suppressHeader = $val;
    }

    // ── Page header ──────────────────────────────────────────
    public function Header()
    {
        if ($this->suppressHeader)
            return;

        $this->SetFillColor(249, 115, 22);
        $this->Rect(0, 0, 297, 3, 'F');

        $this->SetXY(10, 8);
        $this->SetFont('Helvetica', 'B', 16);
        $this->SetTextColor(26, 15, 0);
        $this->Cell(180, 8, $this->reportTitle, 0, 0, 'L');

        $this->SetFont('Helvetica', '', 8);
        $this->SetTextColor(156, 163, 175);
        $this->Cell(0, 8, 'Generated: ' . $this->generatedAt, 0, 1, 'R');

        $this->SetX(10);
        $this->SetFont('Helvetica', '', 8);
        $this->SetTextColor(107, 79, 53);
        $this->Cell(0, 5, 'Filter: ' . $this->filterLabel, 0, 1, 'L');

        $this->SetDrawColor(249, 115, 22);
        $this->SetLineWidth(0.3);
        $this->Line(10, 24, 287, 24);
        $this->Ln(5);
    }

    // ── Page footer ──────────────────────────────────────────
    public function Footer()
    {
        $this->SetY(-12);
        $this->SetDrawColor(249, 115, 22);
        $this->SetLineWidth(0.2);
        $this->Line(10, $this->GetY(), 287, $this->GetY());
        $this->Ln(1);
        $this->SetFont('Helvetica', '', 7.5);
        $this->SetTextColor(156, 163, 175);

        $leftText = 'Project Monitoring System  -  For Public Use';
        if ($this->generatedBy !== '') {
            $leftText = 'Generated by: ' . $this->generatedBy . '  |  ' . $leftText;
        }

        $this->Cell(0, 5, $leftText, 0, 0, 'L');
        $this->Cell(0, 5, 'Page ' . $this->PageNo(), 0, 0, 'R');
    }

    // ── Summary cards row ────────────────────────────────────
    public function SummaryCards(int $total, int $ongoing, int $completed, int $expired): void
    {
        $cards = [
            [$total, 'TOTAL PROJECTS', [255, 247, 237], [249, 115, 22]],
            [$ongoing, 'ONGOING', [239, 246, 255], [37, 99, 235]],
            [$completed, 'COMPLETED', [240, 253, 244], [22, 163, 74]],
            [$expired, 'EXPIRED', [254, 242, 242], [220, 38, 38]],
        ];

        $startX = 10;
        $cardW = 66;
        $cardH = 20;
        $gap = 2.5;
        $startY = $this->GetY();

        foreach ($cards as $i => [$val, $label, $bg, $accent]) {
            $x = $startX + $i * ($cardW + $gap);

            $this->SetFillColor($bg[0], $bg[1], $bg[2]);
            $this->SetDrawColor(220, 200, 180);
            $this->SetLineWidth(0.2);
            $this->RoundedRect($x, $startY, $cardW, $cardH, 2, 'DF');

            $this->SetFillColor($accent[0], $accent[1], $accent[2]);
            $this->Rect($x, $startY, 2.5, $cardH, 'F');

            $this->SetFont('Helvetica', 'B', 20);
            $this->SetTextColor($accent[0], $accent[1], $accent[2]);
            $this->SetXY($x + 6, $startY + 2);
            $this->Cell($cardW - 8, 10, (string) $val, 0, 0, 'L');

            $this->SetFont('Helvetica', 'B', 6.5);
            $this->SetTextColor(107, 79, 53);
            $this->SetXY($x + 6, $startY + 13);
            $this->Cell($cardW - 8, 5, $label, 0, 0, 'L');
        }

        $this->SetY($startY + $cardH + 6);
    }

    // ── Table header row ─────────────────────────────────────
    public function TableHeader(array $cols): void
    {
        $this->SetFillColor(249, 115, 22);
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Helvetica', 'B', 7);
        $this->SetLineWidth(0);

        foreach ($cols as [$label, $width, $align]) {
            $this->Cell($width, 7, strtoupper($label), 0, 0, $align, true);
        }
        $this->Ln();
    }

    // ── Table row ────────────────────────────────────────────
    public function TableRow(array $cells, bool $even): void
    {
        if ($even)
            $this->SetFillColor(255, 250, 245);
        else
            $this->SetFillColor(255, 255, 255);

        $this->SetTextColor(58, 26, 0);
        $this->SetDrawColor(240, 210, 185);
        $this->SetLineWidth(0.1);

        foreach ($cells as [$text, $width, $align, $bold]) {
            $this->SetFont('Helvetica', $bold ? 'B' : '', 7.5);
            $this->Cell($width, 7, $text, 'B', 0, $align, true);
        }
        $this->Ln();
    }

    public function countWrappedLines(
        string $text,
        float $width,
        float $fontSize = 7.5,
        string $fontStyle = '',
        string $fontFamily = 'Helvetica'
    ): int {
        $text = trim(str_replace(["\r\n", "\r"], "\n", $text));
        if ($text === '') {
            return 1;
        }

        $savedFamily = $this->FontFamily;
        $savedStyle = $this->FontStyle;
        $savedSize = $this->FontSizePt;
        $this->SetFont($fontFamily, $fontStyle, $fontSize);

        $lineCount = 0;
        foreach (explode("\n", $text) as $line) {
            $line = trim($line);
            if ($line === '') {
                $lineCount++;
                continue;
            }

            $tokens = preg_split('/(\s+)/u', $line, -1, PREG_SPLIT_DELIM_CAPTURE);
            $current = '';
            $currentLines = 0;

            foreach ($tokens as $token) {
                if ($token === '') {
                    continue;
                }

                if (preg_match('/^\s+$/u', $token) === 1) {
                    if ($current !== '') {
                        $current .= $token;
                    }
                    continue;
                }

                $candidate = $current === '' ? $token : $current . $token;
                if ($this->GetStringWidth($candidate) <= $width || $current === '') {
                    $current = $candidate;
                    continue;
                }

                $currentLines++;
                $current = $token;

                if ($this->GetStringWidth($current) > $width) {
                    $overflow = [];
                    $fragment = '';

                    foreach (preg_split('//u', $current, -1, PREG_SPLIT_NO_EMPTY) as $char) {
                        $trial = $fragment . $char;
                        if ($this->GetStringWidth($trial) > $width && $fragment !== '') {
                            $overflow[] = $fragment;
                            $fragment = $char;
                        } else {
                            $fragment = $trial;
                        }
                    }

                    if ($fragment !== '') {
                        $overflow[] = $fragment;
                    }

                    $current = array_pop($overflow) ?? '';
                    $currentLines += count($overflow);
                }
            }

            if ($current !== '') {
                $currentLines++;
            }

            $lineCount += max(1, $currentLines);
        }

        $this->SetFont($savedFamily, $savedStyle, $savedSize);

        return max(1, $lineCount);
    }

    // ── Row height calculator (extracted so controller can pre-check overflow) ──
    public function calculateRowHeight(array $texts, array $widths): float
    {
        $rowH = self::ROW_MIN_HEIGHT_MM;
        foreach ($texts as $j => $text) {
            if ($text === '' || !isset($widths[$j])) {
                continue;
            }

            $fontStyle = $j === 1 ? 'B' : '';
            $wrappedLines = $this->countWrappedLines((string) $text, $widths[$j], 7.5, $fontStyle);
            if ($wrappedLines > 1) {
                $rowH = max(
                    $rowH,
                    self::ROW_MIN_HEIGHT_MM
                    + (($wrappedLines - 1) * self::ROW_LINE_HEIGHT_MM)
                    + (self::ROW_VERTICAL_PADDING_MM * 2)
                );
            }
        }

        return $rowH;
    }

    // ── Project row ──────────────────────────────────────────
    public function ProjectRow(
        int $num,
        string $title,
        string $inCharge,
        string $location,
        string $contractor,
        string $amount,
        string $started,
        string $expiry,
        string $slipStr,
        array $slipColor,
        string $statusLabel,
        array $statusBg,
        array $statusFg,
        bool $even
    ): void {
        $fillColor = $even ? [255, 250, 245] : [255, 255, 255];

        $widths = [8, 55, 32, 30, 32, 30, 25, 25, 20, 20];
        $aligns = ['C', 'L', 'L', 'L', 'L', 'R', 'C', 'C', 'C', 'C'];
        $texts = [$num, $title, $inCharge, $location, $contractor, $amount, $started, $expiry, '', ''];

        $rowH = $this->calculateRowHeight($texts, $widths);
        $rowY = $this->GetY();
        $leftX = $this->lMargin; // 10

        // Extra vertical padding keeps wrapped text from touching the next row.
        $rowH = max($rowH, self::ROW_MIN_HEIGHT_MM + (self::ROW_VERTICAL_PADDING_MM * 2));

        // Draw the full-row background fill first (single rect per column)
        $x = $leftX;
        foreach ($widths as $w) {
            $this->SetFillColor($fillColor[0], $fillColor[1], $fillColor[2]);
            $this->Rect($x, $rowY, $w, $rowH, 'F');
            $x += $w;
        }

        // Draw text per column, top-aligned inside the (possibly taller) row
        $x = $leftX;
        foreach ($texts as $j => $text) {
            if ($j >= 8) {
                $x += $widths[$j];
                continue;
            } // slippage/status drawn separately below

            $fontStyle = $j === 1 ? 'B' : '';
            $this->SetFont('Helvetica', $fontStyle, 7.5);
            $this->SetTextColor(58, 26, 0);

            $lines = $this->countWrappedLines((string) $text, $widths[$j], 7.5, $fontStyle);
            $textBlockH = $lines * self::ROW_LINE_HEIGHT_MM;
            $padTop = max(0, ($rowH - $textBlockH) / 2); // vertically center within the row

            $this->SetXY($x, $rowY + $padTop);
            $this->MultiCell($widths[$j], self::ROW_LINE_HEIGHT_MM, (string) $text, 0, $aligns[$j], false);

            $x += $widths[$j];
        }

        // Bottom border for the whole row
        $this->SetDrawColor(240, 210, 185);
        $this->SetLineWidth(0.1);
        $this->Line($leftX, $rowY + $rowH, $x, $rowY + $rowH);

        // Slippage column (unchanged logic, just repositioned against new rowH)
        $slipX = $leftX;
        foreach (array_slice($widths, 0, 8) as $w)
            $slipX += $w;

        $this->SetFont('Helvetica', 'B', 7.5);
        $this->SetTextColor($slipColor[0], $slipColor[1], $slipColor[2]);
        $this->SetXY($slipX, $rowY + max(0, ($rowH - self::ROW_LINE_HEIGHT_MM) / 2));
        $this->Cell(20, self::ROW_LINE_HEIGHT_MM, $slipStr, 0, 0, 'C');

        // Status badge should follow the row height so it stays centered and aligned.
        $statusX = $slipX + 20;
        $statusCellH = max(5.0, $rowH - 2.0);
        $statusCellY = $rowY + max(0, ($rowH - $statusCellH) / 2);

        $this->SetFillColor($statusBg[0], $statusBg[1], $statusBg[2]);
        $this->SetTextColor($statusFg[0], $statusFg[1], $statusFg[2]);
        $this->SetFont('Helvetica', 'B', 6.5);
        $this->SetXY($statusX + 1, $statusCellY);
        $this->Cell(18, $statusCellH, $statusLabel, 0, 0, 'C', true);

        $this->SetXY($leftX, $rowY + $rowH);
        $this->SetTextColor(58, 26, 0);
    }

    // ── Status badge helper ──────────────────────────────────
    public function StatusBadge(string $status, float $x, float $y): void
    {
        $map = [
            'completed' => [[240, 253, 244], [22, 163, 74], 'Completed'],
            'expired' => [[254, 242, 242], [220, 38, 38], 'Expired'],
            'expiring' => [[255, 251, 235], [217, 119, 6], 'Expiring'],
            'ongoing' => [[239, 246, 255], [37, 99, 235], 'Ongoing'],
        ];

        [$bg, $fg, $label] = $map[$status] ?? $map['ongoing'];

        $this->SetFillColor($bg[0], $bg[1], $bg[2]);
        $this->SetTextColor($fg[0], $fg[1], $fg[2]);
        $this->SetFont('Helvetica', 'B', 6.5);
        $this->SetXY($x + 1, $y + 1);
        $this->Cell(21, 5, $label, 0, 0, 'C', true);
    }

    // ── Rounded rectangle helper ─────────────────────────────
    public function RoundedRect(float $x, float $y, float $w, float $h, float $r, string $style = ''): void
    {
        $k = $this->k;
        $hp = $this->h;
        $style = $style === 'F' ? 'f' : ($style === 'DF' || $style === 'FD' ? 'B' : 'S');

        $this->_out(sprintf(
            'q %.2F %.2F %.2F %.2F %.2F %.2F c %.2F %.2F %.2F %.2F %.2F %.2F c %.2F %.2F %.2F %.2F %.2F %.2F c %.2F %.2F %.2F %.2F %.2F %.2F c %s Q',
            ($x + $r) * $k,
            ($hp - $y) * $k,
            ($x + $r) * $k,
            ($hp - $y) * $k,
            $x * $k,
            ($hp - $y) * $k,
            $x * $k,
            ($hp - ($y + $r)) * $k,
            $x * $k,
            ($hp - ($y + $h - $r)) * $k,
            $x * $k,
            ($hp - ($y + $h)) * $k,
            ($x + $r) * $k,
            ($hp - ($y + $h)) * $k,
            ($x + $w - $r) * $k,
            ($hp - ($y + $h)) * $k,
            ($x + $w) * $k,
            ($hp - ($y + $h)) * $k,
            ($x + $w) * $k,
            ($hp - ($y + $h - $r)) * $k,
            ($x + $w) * $k,
            ($hp - ($y + $r)) * $k,
            ($x + $w) * $k,
            ($hp - $y) * $k,
            ($x + $w - $r) * $k,
            ($hp - $y) * $k,
            ($x + $r) * $k,
            ($hp - $y) * $k,
            $style
        ));
    }

    // ── Portrait detail-report header (with logo) ────────────
    public function DetailHeader(): void
    {
        $logoPath = public_path('assets/app_logo.png');

        $this->SetFillColor(249, 115, 22);
        $this->Rect(0, 0, 210, 3, 'F');

        if (file_exists($logoPath)) {
            $this->Image($logoPath, 15, 4, 18, 0, 'PNG');
        }
        $rightLogoPath = public_path('assets/province_seal.png');
        if (file_exists($rightLogoPath)) {
            $this->Image($rightLogoPath, 175, 4, 18, 0, 'PNG');
        }

        $this->SetXY(0, 9);
        $this->SetFont('Helvetica', 'B', 14);
        $this->SetTextColor(107, 79, 53);
        $this->Cell(210, 8, 'PROJECT DETAIL REPORT', 0, 1, 'C');

        $this->SetX(0);
        $this->SetFont('Helvetica', '', 8);
        $this->SetTextColor(100, 100, 100);
        $this->Cell(210, 5, 'Generated: ' . $this->generatedAt, 0, 1, 'C');

        $this->SetDrawColor(249, 115, 22);
        $this->SetLineWidth(0.4);
        $this->Line(15, $this->GetY() + 1, 195, $this->GetY() + 1);
        $this->SetLineWidth(0.2);
        $this->SetDrawColor(0, 0, 0);
        $this->SetTextColor(0, 0, 0);

        $this->SetY($this->GetY() + 5);
    }

    /**
     * Returns the PDF_REMARKS_MAX_LENGTH constant so controllers
     * can use it without hard-coding the value.
     */
    public static function remarksMaxLength(): int
    {
        return self::PDF_REMARKS_MAX_LENGTH;
    }
}