<?php

use App\Services\ProjectReportPdf;

test('first page footer includes the generating user', function () {
    $pdf = new ProjectReportPdf('P', 'mm', 'A4');
    $pdf->SetCompression(false);
    $pdf->setGeneratedAt('July 15, 2026 10:30 AM');
    $pdf->setGeneratedBy('Jane Doe');
    $pdf->AddPage();

    $output = $pdf->Output('S');

    expect($output)->toContain('Generated by: Jane Doe');
});
